### ISSUE TITLE
Support for Environment Variable in Group Policy and Registry Keys

### ISSUE THREAD

**Issue by mikey32230** [pseymour/MakeMeAdmin#18]
Is there a solution or workaround for more dynamic assignment of Users/Groups allowed or denied rights via the MakeMeAdmin GPO Templates or Registry Keys?

For example, support for things like: 
%DomainName%\\%LogonUser%
%DomainName%\Example-%ComputerName%-Group

This would allow for simpler use of Group Policy for more dynamically deploying this solution at large scale.

Obviously not all environment variables need supported, however key items like the following would be extremely helpful and practical:
%DomainName%
%ComputerName%
%LogonUser%
%LogonUserSid%

List of Environment Variables: https://evotec.xyz/environment-variables-in-group-policy-preferences/

**Comment by pseymour** [comment]
Couple of things... 

Yes, real environment variables are supported. Those are expanded out by the Make Me Admin service before checking whether the user is authorized. These variables would be anything that you could see by running the `set` command in a command prompt or `Get-ChildItem Env:*` in PowerShell.

The article you linked is incorrectly titled with "Environment Variables." Those are special variables allowed by the Group Policy Preferences, more accurately called [preference process variables](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn789194(v=ws.11)).  Make Me Admin cannot expand those out, as they are specific to Group Policy Preferences extensions.

That being said, you can use the GPP variables to create the registry entries for Make Me Admin. For example, if I wanted to use a local group on each computer to control access, I could do this:

![image](https://user-images.githubusercontent.com/39745121/94952174-8e6b8400-04b3-11eb-8e44-91874c26491e.png)

Or, I could keep a separate group for each computer in my domain, and use something like `%DomainName%\Make Me Admin - %ComputerName%`.

I would be careful using any variables related to the user, because the process that does the checking runs as the System account, and the "user" is going to be that user (SYSTEM), not the interactively logged-on user.  But really, if you're going to allow the logged on user, that's just going to allow anyone who logs on to gain admin rights. It would be easier to just remove that registry entry entirely; the effect would be the same.

**Comment by mikey32230** [comment]
@pseymour Thank you for the quick response and advice!
I'm happy to learn something new :)

I was able to test this out and confirm it works, however it then brings up additional comments/issues/questions.

1. Using GPP variables to create a registry entry (e.g. %DomainName%\Make Me Admin - %ComputerName%):
- This works well when there is an active connection to a Domain Controller.
- Unfortunately this does not work well when working offline. It appears the user account cached creds/token does not retain the group name, only the SID. And there is no way to dynamically assign a domain group SID with the GPP variables.
- Fortunately, it does appear I'm able to workaround this by creating a local group via GPO (e.g. %ComputerName%\MakeMeAdminAllowed), then nesting a domain group as a member (E.g. %DomainName\MakeMeAdmin-%ComputerName%). Then finally setting the local group as the Allowed Entity in the registry key.


I'd be happy to create separate issues/enhancement items for this:

1. I've noticed that MakeMeAdmin does not prompt user for authentication when the user selects "Grant Me Administrator Rights". It would be a nice feature and additional layer of security if the user could be prompted to re-authenticated (against cached creds if offline or domain creds if online). I think both of these checks would be fairly straight forwards to do.
- This just adds a nice additional layer of security, that someone cannot simply walk up to an unlocked computer and immediately elevate.

2. I've also noticed that MakeMeAdmin does not allow for user input/comments for why they are elevating. It would be useful if this could be an optional field that could optionally be required. This would be useful for logging purposes and for potentially understanding elevation use-case.


Again, I really appreciate your work on creating this application and your response!

**Comment by pseymour** [comment]
#2 is the shorter reply... There is already [an issue for this](https://github.com/pseymour/MakeMeAdmin/issues/3). I think it works, but I haven't heard much feedback.

#1: I suppose an option could be added to authenticate after requesting rights. I'm not sure what the benefit would be. Even if an attacker walks up to an unattended machine and gains admin rights, they still have to enter credentials to satisfy any UAC prompts. So really, all they can do is add the account to the Administrators group. They can't actually do anything without knowing the creds.

**Comment by mikey32230** [comment]
@pseymour wow thanks again! I apologize for not knowing or noticing some of these things. Looks like you already have a lot of this covered in one way or another. I really appreciate the help with this and advice!
