### ISSUE TITLE
Slowness when initializing "Checking Administrator Status..."

### ISSUE THREAD

**Issue by mikey32230** [pseymour/MakeMeAdmin#19]
For some reason I've noticed MakeMeAdmin is often/occasionally quite slow to initialize as it checks If you are allowed to Ask for Admin rights (e.g. "Checking Administrator Status...")

This is inconsistent, and is not always slow/delayed. But quite often the initialization can take from 5-15 seconds. Other times it is near instant.

Is there a particular reason this might be occurring (if you've ever noticed it)?

**Comment by pseymour** [comment]
Are you using the released version of 2.3?  If so, try the installers that are currently in the master branch. @martshep made some significant performance improvements in this area.

**Comment by mikey32230** [comment]
> Are you using the released version of 2.3? If so, try the installers that are currently in the master branch. @martshep made some significant performance improvements in this area.

I was initially using 2.3 (master) several weeks ago and I thought I recalled slowness at that time. However, over the past couple weeks I switched to using the Reason-Dialog branch which I've noticed the issue most recently.

However, since switching back to master today for some brief testing I do not notice any slowness so far. Any chance some of the other branches/features can get merged into master?

Thank you

**Comment by pseymour** [comment]
I would feel better about merging the reason dialog into master if someone would test each option (the drop-down and the free-form).  That way, I could blame someone else if it's wrong. :)

**Comment by mikey32230** [comment]
> I would feel better about merging the reason dialog into master if someone would test each option (the drop-down and the free-form). That way, I could blame someone else if it's wrong. :)

I understand, I did test this and I can more. I'm not sure how truly rigorus testing is needed.
Obviously I didn't know about the Enum (I didn't see it documented so I had no idea), but I can test that piece as well.

Most of it seemed to work really well and as expected (including logging of comments) what I specified here (and you responded to):
https://github.com/pseymour/MakeMeAdmin/issues/3#issuecomment-708651703

Thanks!

**Comment by pseymour** [comment]
I'm just looking for basic testing of the two ways of doing reason-prompting. I'm sure some bugs will slip through, but I just want someone who didn't write it, to test it.

**Comment by PeetMcK** [comment]
The UI is pretty solid for the reason prompting. But the instruction text is as clear as it could be. `Please provide a reason for requesting administrator rights.` makes it pretty clear what's happening in the window, but not necessarily the specifics of what needs to be done. I think it would be great if that text (as well as most of the rest of the text though out the app ... i.e "Request Administrator Privileges" instead of "Grant Me Administrator Rights") could be replaced by GP/Registry Keys. 

For example, if I'm only providing a drop down list the text should read `Please select a reason from the dropdown below for requesting administrator rights.`

Or if I'm allowing free form and a drop down `Please select a reason from the dropdown below for requesting administrator rights. If nothing in the list works, please select Other and enter a reason in the text box.` (Maybe too long but you get the gist).

It _may_ be better for some folks to not have the dropdown populated when first presenting it. Or dis-allow the first choice in the list so it can be set to something like `Select a reason ...`

<img width="264" alt="Screen Shot 2021-03-04 at 1 42 27 AM" src="https://user-images.githubusercontent.com/68706879/109935542-f1439000-7c8a-11eb-9c65-b1a6835e60ab.png">

I was going to mention that the input dialogue should have been grayed out but, I actually prefer that you pop the drop down to `Other`. 

A setting for min/max characters allowed in the free form dialog box would be appreciated. I'm unsure how your syslog is implemented, but I understand it can be possible to have messages that are too large to transfer and that can cause problems. Actually this is a big one. I tried to paste the full text of Catcher in the Rye as a reason and crashed the UI. 

<img width="445" alt="Screen Shot 2021-03-04 at 2 03 37 AM" src="https://user-images.githubusercontent.com/68706879/109939092-f35b1e00-7c8d-11eb-9534-85e677a912f0.png">

I noticed that the event log for the reason doesn't include the username of the requester. I do understand that it's in the next event, but for monitoring the log and tying in an alert it could prove simpler to include the username in the event ...`DOMAIN\User provided the following reason for administrator rights: Other: Some reason or another.`  or `Reason for administrator rights: User: DOMAIN\USER Reason: Other: Some reason or another.` instead of `The user provided the following reason for administrator rights: Other: Some reason or another.`

If you have any questions, I'm happy to provide more feedback.

**Comment by PeetMcK** [comment]
I am also getting a full 10+ second delay with both the current release and the Reason-Dialog branch downloaded today. 

It seems to be on the first launch after login and after updating the GPO. It is quite consistent at around 10ish seconds.

**Comment by PeetMcK** [comment]
I can attest that the `Master` branch is a rocket-ship in comparison to the 2.3 release and the` reason-dialog ` branch. @martshep big props for the speedier code Dropping the `Exit` button in the UI is also a visual plus.
