### ISSUE TITLE
Make Me Admin Service Error

### ISSUE THREAD

**Issue by michaellopez2** [pseymour/MakeMeAdmin#39]
Hello,

Just want to start by saying I love this tool and have been using it for a couple of years now. I have just recently ran into a pc error where the app service will not start (screenshot provided). I have tried to completely remove the application and re-install to no avail. I am constantly hit with this error. My one take away is that this is only happening on one machine and all the other machines are operating normally.  Was wondering if there is a setting I am missing or other issue. Thank you for all your assistance.

[Make me admin error.docx](https://github.com/pseymour/MakeMeAdmin/files/6453681/Make.me.admin.error.docx)

Mike

**Comment by pseymour** [comment]
This is generally caused by a corrupted `users.xml` file, which is where Make Me Admin stores the list of users it needs to keep track of. Search for a `users.xml` file that is in a folder named for Make Me Admin, and delete it.  Depending on which version you're on, it'll be in one of two places.

`Get-ChildItem -Path "C:\" -Filter "users.xml" -Recurse -Force -ErrorAction SilentlyContinue`
