### ISSUE TITLE
Question:  Is it recommended yo use the 2.3 installer or the latest in the Repo?

### ISSUE THREAD

**Issue by EYEVO** [pseymour/MakeMeAdmin#41]
I saw the latest release is nearly 3 years old, and the installer in the Repo has debug in the name what would you recommend to use for production?

**Comment by pseymour** [comment]
The safe bet is the latest released version, 2.3.  You can use the latest installers in the repo if you want to test features that are being worked on (the reason-for-rights dialog box, for example).

**Comment by mikey32230** [comment]
@pseymour I think there is some confusion do to a possible mistake on the Wiki page.

For this line: _You can download installers for the latest version, 2.3, from the GitHub repository._ You are currently linking to the [v2.3-fr installer](https://github.com/pseymour/MakeMeAdmin/tree/v2.3-fr/Installers). This through me for a loop at first because it isn't compatible with many of the setting found in Master and even fails to install with some configurations. 

Do you mean for the wiki to point to the latest installers in the Master branch?

Also unrelated question, perhaps I can create a separate _issue_ if needed, but what all the **remoting** settings are intended for (e.g. Allow Remote Requests). Is this supposed to be if I RDP from some unrelated machine into a machine with MakeMeAdmin installed, does it allow me to elevate with MakeMeAdmin through the RDP Session? If this is the case, I don't seem to be able to get that work. Or am I misinterpreting the purpose of this feature?
