### ISSUE TITLE
I uninstalled make me admin because I got tired of it. now I'm locked out of administrator rights and have no way to restore it

### ISSUE THREAD

**Issue by g-doh** [pseymour/MakeMeAdmin#57]
I uninstalled make me admin today. but after a reboot My admin rights are still not restored... what can I do??

**Comment by g-doh** [comment]
I cannot give myself admin rights because that takes admin rights. I cannot reinstall make me admin because that also needs admin rights. and I cannot find an uninstall method

**Comment by g-doh** [comment]
it is a home machine ... and i cannot even enter user account settings without admin rights

**Comment by pseymour** [comment]
Right, that's why I said what I said. The Administrator account's password needs to be something you know, if it isn't already, and the account needs to be enabled, if it's disabled.

You had to have administrator credentials to install MMA, and I'm supposing you used MMA to remove those rights. Now you've removed MMA without having a backout plan.

**Comment by sunvis0r** [comment]
Agree with g-doh. I installed MakeMeAdmin as utility to fix security troubles that I haven't time to configure on clean Windows machine. It's suppose that I should change something with admin rights and then the program returns status quo back.

I like MakeMeAdmin idea, but now I have more access troubles
